// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class HappyTest {
  private static IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [ClassInitialize()]
        public static void ClassInit(TestContext context)
        {
            MessageBox.Show("ClassInit " + context.TestName);
        }

  [AssemblyInitialize()]
        public static void AssemblyInit(TestContext context)
        {
            MessageBox.Show("AssemblyInit " + context.TestName);
        }

  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void happy() {
    // Test name: Happy
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.google.com/");
    // 2 | setWindowSize | 1936x1056 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    // 3 | type | name=q | happy
    driver.FindElement(By.Name("q")).SendKeys("happy");
    // 4 | sendKeys | name=q | ${KEY_ENTER}
    driver.FindElement(By.Name("q")).SendKeys(Keys.Enter);
    // 5 | click | linkText=Images | 
    driver.FindElement(By.LinkText("Images")).Click();
    // 6 | click | linkText=Videos | 
    driver.FindElement(By.LinkText("Videos")).Click();
    // 7 | click | css=.g:nth-child(1) .LC20lb > span | 
    driver.FindElement(By.CssSelector(".g:nth-child(1) .LC20lb > span")).Click();
  }
}
